# Christian Cortez cssc1965
#  CS530, Spring 2020
#  Assignment #2 SIC/XE Dissasembler
#  File: makefile
#
# CC tells makefile to compile using g++ for .cpp files
# FILEX, for X = 1, 2, 3, etc. are the names of the files to be compiled
# OFLAG is the -o flag for g++
# OUT is the name of the output file

CC = g++
FILE1 = "dxe.cpp"
FILE2 = "fileReader.cpp"
FILE3 = "Symtab.cpp"
FILE4 = "Processor.cpp"
FILE5 = "OpcodeTable.cpp"
OFLAG = -o
WFLAG = -w
OUT = "dxe"

all:
	$(CC) $(FILE1) $(FILE2) $(FILE3) $(FILE4) $(FILE5) $(WFLAG) $(OFLAG) $(OUT)
